apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ1cy1hc2hidXJuLTEub2Npci5pbyI6eyJ1c2VybmFtZSI6ImlkZDJvaXpwOHh2Yy9jb2xlbWFuLnJ5YW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiJcdTAwM2NdVUlUb3d1M1l4cChLejJuUSNnIiwiZW1haWwiOiJjb2xlbWFuLnJ5YW5AZ21haWwuY29tIiwiYXV0aCI6ImFXUmtNbTlwZW5BNGVIWmpMMk52YkdWdFlXNHVjbmxoYmtCbmJXRnBiQzVqYjIwNlBGMVZTVlJ2ZDNVeldYaHdLRXQ2TW01UkkyYz0ifX19
kind: Secret
metadata:
  name: ocir-secret
  namespace: veribits-com
type: kubernetes.io/dockerconfigjson
